name: figgy
services:
  test_solr:
    type: solr:7
    portforward: true
    core: figgy-core-test
    config:
      dir: solr/config
  test_db:
    type: postgres:10
    portforward: true
  # dev_solr:
  #   type: solr:7
  #   portforward: true
  #   core: figgy-core-dev
  #   config:
  #     dir: solr/config
