<% lando_configuration = JSON.parse(`lando info --format json`).group_by{|x| x["service"]}["test_db"][0] %>
development: &default
  adapter: postgresql
  database: figgy_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 30)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 20)) %>
  timeout: 5000

test:
  <<: *default
  host: <%= ENV["FIGGY_DB_HOST"] || lando_configuration["external_connection"]["host"] %>
  port: <%= lando_configuration["external_connection"]["port"] %>
  username: <%= Figgy.read_only_mode ? ENV["FIGGY_DB_RO_USERNAME"] : ENV["FIGGY_DB_USERNAME"] || lando_configuration["creds"]["user"] %>
  password: <%= Figgy.read_only_mode ? ENV["FIGGY_DB_RO_PASSWORD"] : ENV["FIGGY_DB_PASSWORD"] || lando_configuration["creds"]["password"] %>
  database: figgy_test

production: &deploy
  <<: *default
  adapter: postgresql
  database: <%= ENV["FIGGY_DB"] %>
  host: <%= ENV["FIGGY_DB_HOST"] %>
  username: <%= Figgy.read_only_mode ? ENV["FIGGY_DB_RO_USERNAME"] : ENV["FIGGY_DB_USERNAME"] %>
  password: <%= Figgy.read_only_mode ? ENV["FIGGY_DB_RO_PASSWORD"] : ENV["FIGGY_DB_PASSWORD"] %>

staging: *deploy
